#ifndef _TRIANGLE_SETUP_H_
#define _TRIANGLE_SETUP_H_

#define TRIANGLE_SETUP_LOCAL_SIZE_X (64)
#define TRIANGLE_SETUP_LOCAL_SIZE_Y (1)
#define TRIANGLE_SETUP_LOCAL_SIZE_Z (1)

#endif // _TRIANGLE_SETUP_H_
