#version 450

#include "../../../TriangleSetupUtil.comp"
#include "Clipping.h"

layout(local_size_x = CLIPPING_LOCAL_SIZE_X, local_size_y = CLIPPING_LOCAL_SIZE_Y, local_size_z = CLIPPING_LOCAL_SIZE_Z) in;

layout(push_constant) uniform TestParams {
    u32 triangleCount;
};

layout(set = 0, binding = 0, std430) readonly buffer Vertecies {
    vec4 vertecies[][3];
};

layout(set = 0, binding = 1, std430) writeonly buffer ClippedVertecies {
    vec3 clippedVertecies[][6];
};

layout(set = 0, binding = 2, std430) writeonly buffer ClippedVertexCounts {
    u32 clippedVertexCounts[];
};

void main() {
    if (gl_GlobalInvocationID.x >= triangleCount) {
        return;
    }

    const vec4 triangle[3] = vertecies[gl_GlobalInvocationID.x];
    vec3 barys[6];
    clippedVertexCounts[gl_GlobalInvocationID.x] = clip(triangle, barys);
    clippedVertecies[gl_GlobalInvocationID.x] = barys;
}
