#version 450

#include "../../../TriangleSetupUtil.comp"

layout(local_size_x = 64) in;

layout(push_constant) uniform TestParams {
    u32 triangleCount;
};

layout(set = 0, binding = 0, std140) readonly buffer Vertecies {
    vec4 vertecies[][3];
};

layout(set = 0, binding = 1, std140) writeonly buffer ClippedVertecies {
    vec3 clippedVertecies[][6];
};

layout(set = 0, binding = 2, std140) writeonly buffer ClippedVertexCounts {
    u32 clippedVertexCounts[];
};

void main() {
    if (gl_GlobalInvocationID.x >= triangleCount) {
        return;
    }

    const vec4 triangle[3] = vertecies[gl_GlobalInvocationID.x];
    clippedVertexCounts[gl_GlobalInvocationID.x] = clip(triangle, clippedVertecies[gl_GlobalInvocationID.x]);
}
