#version 450

#include "../../../TriangleSetupUtil.comp"

layout(local_size_x = 64) in;

layout(push_constant) uniform TestParams {
    u32 vertexCount;
    u32 packedViewport;
};

layout(set = 0, binding = 0, std430) readonly buffer Vertecies {
    vec4 vertecies[];
};

layout(set = 0, binding = 1, std430) writeonly buffer NDCVertecies {
    vec4 ndcVertecies[];
};

layout(set = 0, binding = 2, std430) writeonly buffer SubpixelVertecies {
    uvec2 subpixelVertecies[];
};

void main() {
    const u32 i = gl_GlobalInvocationID.x;
    if (i >= vertexCount) {
        return;
    }

    u16vec2 viewport = unpack16(packedViewport);

    vec4 ndc = toNDC(vertecies[i]);
    ndcVertecies[i] = ndc;
    subpixelVertecies[i] = toSubpixel(viewport, ndc.xy);
}
