IF (NOT ${Vulkan_FOUND})
    FIND_PACKAGE(Vulkan REQUIRED)
ENDIF

function(add_shader TARGET_NAME SHADER DESTINATION)
    add_custom_target(${TARGET_NAME} ALL
        COMMAND ${Vulkan_GLSLC_EXECUTABLE} -o ${CMAKE_CURRENT_BINARY_DIR}/${DESTINATION} ${CMAKE_CURRENT_SOURCE_DIR}/${SHADER}
        VERBATIM
    )
endfunction()
