#pragma once

#include <vulkan/vulkan.hpp>

#include "AutoGeneratedKernelResources.h"

#include "shared/compatibility.h"

namespace vkr {
namespace gpu {

vk::ShaderModuleCreateInfo describeSimple();
vk::ShaderModuleCreateInfo describeTriangleSetup();

} // gpu
} // vkr
