#pragma once

#include <vulkan/vulkan.h>

#include "AutoGeneratedKernelResources.h"

#include "shared/compatibility.h"

namespace vkr {
namespace gpu {

VkShaderModuleCreateInfo describeTriangleSetup();

} // gpu
} // vkr
